
function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	g = go.get("/go#sprite","xxx")
	print(g)
	self.t = 0 
end
function update(self, dt)
	self.t = self.t + dt -- <2>
	go.set("/go#sprite", "xxx", vmath.vector4(self.t, 0, 0, 0))

end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("Touch!")
	end
end